function Hd = Channel_Lowpass_FIR_Coeff(Fs)
%CHANNEL_LOWPASS_FIR_COEFF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 20-May-2023 13:14:25

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
% Fs = 120;  % Sampling Frequency

Fpass = 15e3;              % Passband Frequency
Fstop = 17e3;              % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
